spring:
  application:
    name: desafioTecnico
  datasource:
    url: jdbc:mysql://localhost:3306/rpeteste
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
